#!/usr/bin/env bash

BASH_DEBUG="${BASH_DEBUG:=}"
([ "${BASH_DEBUG}" == "true" ] || [ "${BASH_DEBUG}" == "1" ] ) && set -o xtrace
set -o errexit
set -o nounset
set -o pipefail
shopt -s dotglob
trap "exit" INT

# Directory where this script resides
THIS_DIR=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)

# Where the source code is
PROJECT_ROOT_DIR="$(realpath ${THIS_DIR}/..)"

source "${PROJECT_ROOT_DIR}/.env.example"
if [ -f "${PROJECT_ROOT_DIR}/.env" ]; then
  source "${PROJECT_ROOT_DIR}/.env"
fi

if [ "${VERBOSE:=0}" == "1" ]; then
set -x
fi

export PAGER=''
DATA_DOWNLOADED_DIR="data_downloaded"
DATA_OUTPUT_DIR="data_output"

echo ""
echo "Index file diff:"
git --no-pager diff --color=always --no-index --minimal "${DATA_DOWNLOADED_DIR}/index.json" "${DATA_OUTPUT_DIR}/index.json" \
  | grep -wv -e 'zip-bundle' \
  | grep -wv -e 'Binary files' \
  || true

echo ""
echo "List of changed files (excluding zip bundles):"
git --no-pager diff --color=always --no-index --name-status "${DATA_DOWNLOADED_DIR}" "${DATA_OUTPUT_DIR}" \
  | grep -wv -e 'zip-bundle' \
  || true
