on:
  pull_request:

concurrency:
  group: fork-${{ github.workflow }}-${{ github.ref_type }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  fork:
    # Run only if it's a fork
    if: ${{ ((github.event_name == 'pull_request') && (github.event.pull_request.head.repo.fork || ((github.event.pull_request.head.repo.full_name || github.event.pull_request.base.repo.full_name) != github.repository))) }}

    runs-on: ubuntu-20.04

    environment:
      name: ${{ github.ref }}

    steps:
      # This fails if the PR contains changes to executable code
      - name: "Check for code changes"
        run: |
          if ! git --no-pager diff --cached --exit-code --name-only origin/master origin/${GITHUB_HEAD_REF} -- . ':!data' ':!data_output'; then
            echo "There are code changes. This is not allowed."
            exit 1
          fi
